Homework 1 - Clean code
GenesisEducationKyiv/main-project-vorobeiDev pull request #2
Opened 2023-06-17 08:13 UTC by vorobeiDev

2023-06-20 06:57 UTC, MlPablo reviewed
There more to review, but for now just fix this mistakes. Overall: separate your logic, make them more general.
My proposal to make structure like this
Services:  EmailService, CurrencyServie
Repository: EmailRepository. 
Handlers: just handlers that has access to services. Services has access to repository. Try it)

2023-06-20 06:57 UTC, MlPablo commented on .env
> +BASE_CRYPTO_EXCHANGE_URL=https://api.coingecko.com
better to set concrete name of service like  `COINGECKO_BASE_URL`

2023-06-21 17:54 UTC, MlPablo requested changes

2023-06-21 17:54 UTC, MlPablo commented on pkg/service/currencyService.go
> +	httpClient *http.Client
No need to store this info. Just call http.DefaultClient.Do()

2023-06-21 17:54 UTC, MlPablo commented on pkg/service/emailService.go
> +	from := os.Getenv("EMAIL_FROM")
send this data to Service constructor. So there no need  to call every time os.Getenv()

2023-06-21 17:54 UTC, MlPablo commented on pkg/service/services.go
> +		ValidationService: NewValidationService(),
FIleService is not a service, but storage in this context.
I still think that Validation should't be a separate service, but methods on domains.

2023-06-21 17:54 UTC, MlPablo commented on pkg/service/currencyService.go
> +}
Bad naming. Try Something more general.
Because Coingecko send response where json tags are concrate name of currency, here better to parse using maps. Read about parsing with maps, for example (https://www.tutorialkart.com/golang-tutorial/golang-convert-json-to-map/#gsc.tab=0). So you will be able to work with any currency

2023-06-21 17:54 UTC, MlPablo commented on pkg/handler/subscribeHandler.go
> +	err := h.services.FileService.WriteToFile(emailData.Email)
For better scaling, handlers shouldn't work with db directly. Try to send this logic into, EmailService like, emailService.SaveEmail()
func (e *emailService) SaveEmail() {
e.fileStorage.WriteToFile(email) // better e.emailRepo.Save(email)

2023-06-21 17:54 UTC, MlPablo commented on pkg/handler/sendEmailHandler.go
> +	emails, err := h.services.FileService.ReadFromFile()
Same as in Subscribe handler

2023-06-21 17:54 UTC, MlPablo commented on pkg/handler/getRateHandler.go
> +	price, err := h.services.CurrencyService.GetBTCPriceInUAH(ctx)
Better h.services.CurrencyService.GetPrice(ctx, BTC, UAH) // BTC UAH should be some entities that sits in separate package

2023-06-26 09:15 UTC, andrey-filenko-quarks-tech commented on cmd/main.go
> +	newServices := service.NewServices()
I guess new* prefix in variables names is redundant

2023-06-26 09:16 UTC, andrey-filenko-quarks-tech commented on pkg/handler/emailHandler.go
> +	ctx := context.Background()
you can get context from c *gin.Context

2023-06-26 09:16 UTC, andrey-filenko-quarks-tech commented on pkg/handler/emailHandler.go
> +	btcRate, err := h.services.CurrencyService.GetPrice(ctx, "bitcoin", "uah")
I guess "bitcoin" and "uah" can be constants

2023-06-26 09:18 UTC, andrey-filenko-quarks-tech commented on pkg/repository/emailRepository.go
> +		return ErrEmailExists
I guess error can be wrapped with some details fmt.Errorf("%w %s", ErrEmailExists, email)

2023-06-26 09:19 UTC, andrey-filenko-quarks-tech commented on pkg/repository/emailRepository.go
> +func (r *EmailRepository) GetAllEmails() ([]string, error) {
Get* prefix is not very idiomatic for golang, I guess this method can be named as AllEmails

2023-06-26 09:20 UTC, andrey-filenko-quarks-tech commented on pkg/service/currencyService.go
> +	baseURL := os.Getenv("COINGECKO_BASE_URL")
url can be passed to NewCurrencyService as argument and be a property of CurrencyService

2023-06-26 09:20 UTC, andrey-filenko-quarks-tech commented on pkg/service/currencyService.go
> +	response, err := http.DefaultClient.Do(request)
httpclient can also be a property of CurrencyService (for example for testing purposes)

2023-06-26 09:22 UTC, andrey-filenko-quarks-tech commented on pkg/service/emailService.go
> +	emailRepository := repository.NewEmailRepository()
you should pass it as argument to constructor, because now you cannot use mock for repository here

2023-06-26 15:47 UTC, MlPablo commented on cmd/main.go
> +	auth := smtp.PlainAuth("", "user@example.com", "password", "smtp.example.com")
Andrii said to add this to part of structs where they used
Like
type handler struct {
client http.Client
}
So env varibales should be as part of construcotr like NewEmailService(email string) ....

2023-06-26 15:47 UTC, MlPablo commented on pkg/handler/handlers.go
> +)
const must be declared on the top of the file
Just name them BTC, UAH

2023-06-26 15:47 UTC, MlPablo commented on pkg/service/currencyService.go
> +		baseURL:    url,
no need to pass httpClient as argument
just do
func .... {
client := http.DefaultClient()
}

2023-06-26 16:49 UTC, merged