Homework 02 - Tests
GenesisEducationKyiv/main-project-vorobeiDev pull request #3
Opened 2023-06-24 11:39 UTC by vorobeiDev

2023-06-25 07:07 UTC, MlPablo commented on pkg/repository/email_repository_test.go
> +func TestSave(t *testing.T) {
You are just checking file creation here. So better to rename test like TestFileCreate or add validation that your test email are in the file.

2023-06-25 07:07 UTC, MlPablo commented on pkg/repository/email_repository_test.go
> +	}
why you aren't using SaveEmail here for several emails?
As I know, when we are testing 1 piece of code, we are suggesting that all others are working. So If your TestSave will failed, then this test will fail also. It's just my opinion

2023-06-25 07:07 UTC, MlPablo commented on pkg/repository/email_repository_test.go
> +	expectedEmails := []string{"test1@example.com", "test2@example.com", "test3@example.com"}
This is bad idea to declare test values several time. Just create this slice on the top of the test and then reuse them on Save and On comparing emails that you get. It will prevent you from typo errors and will keep constancy on your test data.

2023-06-25 07:07 UTC, MlPablo commented on pkg/repository/email_repository_test.go
> +	}()
What is this function for?

2023-06-27 22:03 UTC, oleksandr-kh requested changes

2023-06-27 22:03 UTC, oleksandr-kh commented on pkg/handler/subscribe_handler_integration_test.go
> +func TestSubscribeIntegration(t *testing.T) {
Звичайно добре мати тест, який перевіряє позитивний сценарій, але в даному кейсі точно було б добре ще перевірити негативні сценарії по типу
- Invalid or missing email
- Invalid email address
- Email already exists

2023-06-27 22:04 UTC, oleksandr-kh commented
хотілось би бачити ще unit тести та e2e
в тебе вийшло два інтеграційних

2023-07-10 07:33 UTC, merged