Homework 03 - SOLID GRASP
GenesisEducationKyiv/main-project-vorobeiDev pull request #4
Opened 2023-06-27 15:24 UTC by vorobeiDev

2023-07-01 17:05 UTC, MlPablo requested changes

2023-07-01 17:05 UTC, MlPablo commented on pkg/service/currency_service.go
> +func NewCurrencyService() ICurrencyService {
just return *CurrencyService object. Define interface in place of usage. Try ireturn linter.

2023-07-01 17:05 UTC, MlPablo commented on pkg/service/currency_service.go
>  	url := os.Getenv("COINGECKO_BASE_URL")
This should be provided as parameter for constructor.

2023-07-01 17:05 UTC, MlPablo commented on pkg/service/email_service.go
1. email_from make as parametr for constructor.
2. Return class, not interface
3. So here you can define IEmailRepository interface and use it in your service. So you will need describe methods that are actualy used. Ex. 
```go
type IEmailRepository interface {
    SaveEmail(email string) error
     //....
}
```

2023-07-01 17:05 UTC, MlPablo commented on pkg/service/services.go
>  		EmailService:    emailService,
Why do you need this?

2023-07-03 22:06 UTC, oleksandr-kh commented on pkg/service/email_service.go
> +type IEmailService interface {
В тебе юзерсервіс має багато відповідальності, він гарний кандидат на god сервіс в якому за самою назвою ніколи не зрозумієш за що саме він відповідальний. Мої поради:
- не має необхідності робити сервіс в якому частина методів просто проксюють на репозиторій. Там де тобі в логіці потрібен репозиторій - використовуй саме репозиторій, а не сервіс який огортає репозиторій
- тоді в тебе EmailService можна перетворити в EmailSender з методом Send який буде відповідати тільки за відправку листа

2023-07-03 22:09 UTC, oleksandr-kh commented on pkg/repository/email_repository.go
> +	RemoveFile() error
Не повинен репозиторій віддавати назовні контракти які вказують на те яке саме сховище використовується (RemoveFile,IsFileExists,CreateFileIfNotExist) 
Тут перевірочне питання буде - якщо я зміню сорс на Mysql, то чи точно підійде це інтерфейс?

2023-07-13 09:36 UTC, merged